# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterkering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Melding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melding', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
